/*
 * Copyright 2020 Twitter, Inc.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.twitter.clientlib.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GenericTweetsTimelineResponseMeta
 */
public class GenericTweetsTimelineResponseMetaTest {
    private final GenericTweetsTimelineResponseMeta model = new GenericTweetsTimelineResponseMeta();

    /**
     * Model tests for GenericTweetsTimelineResponseMeta
     */
    @Test
    public void testGenericTweetsTimelineResponseMeta() {
        // TODO: test GenericTweetsTimelineResponseMeta
    }

    /**
     * Test the property 'newestId'
     */
    @Test
    public void newestIdTest() {
        // TODO: test newestId
    }

    /**
     * Test the property 'oldestId'
     */
    @Test
    public void oldestIdTest() {
        // TODO: test oldestId
    }

    /**
     * Test the property 'previousToken'
     */
    @Test
    public void previousTokenTest() {
        // TODO: test previousToken
    }

    /**
     * Test the property 'nextToken'
     */
    @Test
    public void nextTokenTest() {
        // TODO: test nextToken
    }

    /**
     * Test the property 'resultCount'
     */
    @Test
    public void resultCountTest() {
        // TODO: test resultCount
    }

}
