/*
 * Copyright 2020 Twitter, Inc.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.twitter.clientlib.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.twitter.clientlib.model.RulesRequestSummaryOneOf;
import com.twitter.clientlib.model.RulesRequestSummaryOneOf1;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RulesRequestSummary
 */
public class RulesRequestSummaryTest {
    private final RulesRequestSummary model = new RulesRequestSummary();

    /**
     * Model tests for RulesRequestSummary
     */
    @Test
    public void testRulesRequestSummary() {
        // TODO: test RulesRequestSummary
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'notCreated'
     */
    @Test
    public void notCreatedTest() {
        // TODO: test notCreated
    }

    /**
     * Test the property 'valid'
     */
    @Test
    public void validTest() {
        // TODO: test valid
    }

    /**
     * Test the property 'invalid'
     */
    @Test
    public void invalidTest() {
        // TODO: test invalid
    }

    /**
     * Test the property 'deleted'
     */
    @Test
    public void deletedTest() {
        // TODO: test deleted
    }

    /**
     * Test the property 'notDeleted'
     */
    @Test
    public void notDeletedTest() {
        // TODO: test notDeleted
    }

}
