/*
 * Copyright 2020 Twitter, Inc.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.twitter.clientlib.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RulesRequestSummaryOneOf1
 */
public class RulesRequestSummaryOneOf1Test {
    private final RulesRequestSummaryOneOf1 model = new RulesRequestSummaryOneOf1();

    /**
     * Model tests for RulesRequestSummaryOneOf1
     */
    @Test
    public void testRulesRequestSummaryOneOf1() {
        // TODO: test RulesRequestSummaryOneOf1
    }

    /**
     * Test the property 'deleted'
     */
    @Test
    public void deletedTest() {
        // TODO: test deleted
    }

    /**
     * Test the property 'notDeleted'
     */
    @Test
    public void notDeletedTest() {
        // TODO: test notDeleted
    }

}
