/*
 * Copyright 2020 Twitter, Inc.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.twitter.clientlib.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UsersFollowingCreateResponseData
 */
public class UsersFollowingCreateResponseDataTest {
    private final UsersFollowingCreateResponseData model = new UsersFollowingCreateResponseData();

    /**
     * Model tests for UsersFollowingCreateResponseData
     */
    @Test
    public void testUsersFollowingCreateResponseData() {
        // TODO: test UsersFollowingCreateResponseData
    }

    /**
     * Test the property 'following'
     */
    @Test
    public void followingTest() {
        // TODO: test following
    }

    /**
     * Test the property 'pendingFollow'
     */
    @Test
    public void pendingFollowTest() {
        // TODO: test pendingFollow
    }

}
