/*
 * Copyright 2020 Twitter, Inc.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.twitter.clientlib.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VideoAllOfNonPublicMetrics
 */
public class VideoAllOfNonPublicMetricsTest {
    private final VideoAllOfNonPublicMetrics model = new VideoAllOfNonPublicMetrics();

    /**
     * Model tests for VideoAllOfNonPublicMetrics
     */
    @Test
    public void testVideoAllOfNonPublicMetrics() {
        // TODO: test VideoAllOfNonPublicMetrics
    }

    /**
     * Test the property 'playback0Count'
     */
    @Test
    public void playback0CountTest() {
        // TODO: test playback0Count
    }

    /**
     * Test the property 'playback25Count'
     */
    @Test
    public void playback25CountTest() {
        // TODO: test playback25Count
    }

    /**
     * Test the property 'playback50Count'
     */
    @Test
    public void playback50CountTest() {
        // TODO: test playback50Count
    }

    /**
     * Test the property 'playback75Count'
     */
    @Test
    public void playback75CountTest() {
        // TODO: test playback75Count
    }

    /**
     * Test the property 'playback100Count'
     */
    @Test
    public void playback100CountTest() {
        // TODO: test playback100Count
    }

}
