/*
 * Copyright 2020 Twitter, Inc.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.twitter.clientlib.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

/**
 * Media information being attached to created Tweet. This is mutually exclusive from Quote Tweet Id and Poll.
 */
@ApiModel(description = "Media information being attached to created Tweet. This is mutually exclusive from Quote Tweet Id and Poll.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CreateTweetRequestMedia {
  public static final String SERIALIZED_NAME_MEDIA_IDS = "media_ids";
  @SerializedName(SERIALIZED_NAME_MEDIA_IDS)
  private List<String> mediaIds = null;

  public static final String SERIALIZED_NAME_TAGGED_USER_IDS = "tagged_user_ids";
  @SerializedName(SERIALIZED_NAME_TAGGED_USER_IDS)
  private List<String> taggedUserIds = null;

  public CreateTweetRequestMedia() { 
  }

  public CreateTweetRequestMedia mediaIds(List<String> mediaIds) {
    
    this.mediaIds = mediaIds;
    return this;
  }

  public CreateTweetRequestMedia addMediaIdsItem(String mediaIdsItem) {
    if (this.mediaIds == null) {
      this.mediaIds = new ArrayList<>();
    }
    this.mediaIds.add(mediaIdsItem);
    return this;
  }

   /**
   * A list of Media Ids to be attached to a created Tweet.
   * @return mediaIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of Media Ids to be attached to a created Tweet.")

  public List<String> getMediaIds() {
    return mediaIds;
  }


  public void setMediaIds(List<String> mediaIds) {
    this.mediaIds = mediaIds;
  }


  public CreateTweetRequestMedia taggedUserIds(List<String> taggedUserIds) {
    
    this.taggedUserIds = taggedUserIds;
    return this;
  }

  public CreateTweetRequestMedia addTaggedUserIdsItem(String taggedUserIdsItem) {
    if (this.taggedUserIds == null) {
      this.taggedUserIds = new ArrayList<>();
    }
    this.taggedUserIds.add(taggedUserIdsItem);
    return this;
  }

   /**
   * A list of User Ids to be tagged in the media for created Tweet.
   * @return taggedUserIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of User Ids to be tagged in the media for created Tweet.")

  public List<String> getTaggedUserIds() {
    return taggedUserIds;
  }


  public void setTaggedUserIds(List<String> taggedUserIds) {
    this.taggedUserIds = taggedUserIds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateTweetRequestMedia createTweetRequestMedia = (CreateTweetRequestMedia) o;
    return Objects.equals(this.mediaIds, createTweetRequestMedia.mediaIds) &&
        Objects.equals(this.taggedUserIds, createTweetRequestMedia.taggedUserIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mediaIds, taggedUserIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateTweetRequestMedia {\n");
    sb.append("    mediaIds: ").append(toIndentedString(mediaIds)).append("\n");
    sb.append("    taggedUserIds: ").append(toIndentedString(taggedUserIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("media_ids");
    openapiFields.add("tagged_user_ids");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateTweetRequestMedia.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateTweetRequestMedia' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateTweetRequestMedia> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateTweetRequestMedia.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateTweetRequestMedia>() {
           @Override
           public void write(JsonWriter out, CreateTweetRequestMedia value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateTweetRequestMedia read(JsonReader in) throws IOException {
             JsonObject obj = elementAdapter.read(in).getAsJsonObject();
             Set<Entry<String, JsonElement>> entries = obj.entrySet();//will return members of your object
             // check to see if the JSON string contains additional fields
             for (Entry<String, JsonElement> entry: entries) {
               if (!CreateTweetRequestMedia.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException("The field `" + entry.getKey() + "` in the JSON string is not defined in the `CreateTweetRequestMedia` properties");
               }
             }

             return thisAdapter.fromJsonTree(obj);
           }

       }.nullSafe();
    }
  }
}
