/*
 * Copyright 2020 Twitter, Inc.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.twitter.clientlib.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets PlaceType
 */
@JsonAdapter(PlaceType.Adapter.class)
public enum PlaceType {
  
  POI("poi"),
  
  NEIGHBORHOOD("neighborhood"),
  
  CITY("city"),
  
  ADMIN("admin"),
  
  COUNTRY("country"),
  
  UNKNOWN("unknown");

  private String value;

  PlaceType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PlaceType fromValue(String value) {
    for (PlaceType b : PlaceType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PlaceType> {
    @Override
    public void write(final JsonWriter jsonWriter, final PlaceType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PlaceType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PlaceType.fromValue(value);
    }
  }
}

