/*
 * Copyright 2020 Twitter, Inc.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.twitter.clientlib.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.twitter.clientlib.model.RulesRequestSummaryOneOf;
import com.twitter.clientlib.model.RulesRequestSummaryOneOf1;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import javax.ws.rs.core.GenericType;

import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;

import com.twitter.clientlib.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class RulesRequestSummary extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(RulesRequestSummary.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!RulesRequestSummary.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'RulesRequestSummary' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<RulesRequestSummaryOneOf> adapterRulesRequestSummaryOneOf = gson.getDelegateAdapter(this, TypeToken.get(RulesRequestSummaryOneOf.class));
            final TypeAdapter<RulesRequestSummaryOneOf1> adapterRulesRequestSummaryOneOf1 = gson.getDelegateAdapter(this, TypeToken.get(RulesRequestSummaryOneOf1.class));

            return (TypeAdapter<T>) new TypeAdapter<RulesRequestSummary>() {
                @Override
                public void write(JsonWriter out, RulesRequestSummary value) throws IOException {
                    // check if the actual instance is of the type `RulesRequestSummaryOneOf`
                    if (value.getActualInstance() instanceof RulesRequestSummaryOneOf) {
                        JsonObject obj = adapterRulesRequestSummaryOneOf.toJsonTree((RulesRequestSummaryOneOf)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                    }

                    // check if the actual instance is of the type `RulesRequestSummaryOneOf1`
                    if (value.getActualInstance() instanceof RulesRequestSummaryOneOf1) {
                        JsonObject obj = adapterRulesRequestSummaryOneOf1.toJsonTree((RulesRequestSummaryOneOf1)value.getActualInstance()).getAsJsonObject();
                        elementAdapter.write(out, obj);
                    }

                    throw new IOException("Failed to deserialize as the type doesn't match oneOf schemas: RulesRequestSummaryOneOf, RulesRequestSummaryOneOf1");
                }

                @Override
                public RulesRequestSummary read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonObject jsonObject = elementAdapter.read(in).getAsJsonObject();

                    int match = 0;

                    // deserialize RulesRequestSummaryOneOf
                    try {
                        deserialized = adapterRulesRequestSummaryOneOf.fromJsonTree(jsonObject);
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'RulesRequestSummaryOneOf'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        log.log(Level.FINER, "Input data does not match schema 'RulesRequestSummaryOneOf'", e);
                    }

                    // deserialize RulesRequestSummaryOneOf1
                    try {
                        deserialized = adapterRulesRequestSummaryOneOf1.fromJsonTree(jsonObject);
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'RulesRequestSummaryOneOf1'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        log.log(Level.FINER, "Input data does not match schema 'RulesRequestSummaryOneOf1'", e);
                    }

                    if (match == 1) {
                        RulesRequestSummary ret = new RulesRequestSummary();
                        ret.setActualInstance(deserialized);
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for RulesRequestSummary: %d classes match result, expected 1", match));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, GenericType> schemas = new HashMap<String, GenericType>();

    public RulesRequestSummary() {
        super("oneOf", Boolean.FALSE);
    }

    public RulesRequestSummary(RulesRequestSummaryOneOf o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public RulesRequestSummary(RulesRequestSummaryOneOf1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("RulesRequestSummaryOneOf", new GenericType<RulesRequestSummaryOneOf>() {
        });
        schemas.put("RulesRequestSummaryOneOf1", new GenericType<RulesRequestSummaryOneOf1>() {
        });
    }

    @Override
    public Map<String, GenericType> getSchemas() {
        return RulesRequestSummary.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * RulesRequestSummaryOneOf, RulesRequestSummaryOneOf1
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof RulesRequestSummaryOneOf) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof RulesRequestSummaryOneOf1) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be RulesRequestSummaryOneOf, RulesRequestSummaryOneOf1");
    }

    /**
     * Get the actual instance, which can be the following:
     * RulesRequestSummaryOneOf, RulesRequestSummaryOneOf1
     *
     * @return The actual instance (RulesRequestSummaryOneOf, RulesRequestSummaryOneOf1)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `RulesRequestSummaryOneOf`. If the actual instance is not `RulesRequestSummaryOneOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `RulesRequestSummaryOneOf`
     * @throws ClassCastException if the instance is not `RulesRequestSummaryOneOf`
     */
    public RulesRequestSummaryOneOf getRulesRequestSummaryOneOf() throws ClassCastException {
        return (RulesRequestSummaryOneOf)super.getActualInstance();
    }

    /**
     * Get the actual instance of `RulesRequestSummaryOneOf1`. If the actual instance is not `RulesRequestSummaryOneOf1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `RulesRequestSummaryOneOf1`
     * @throws ClassCastException if the instance is not `RulesRequestSummaryOneOf1`
     */
    public RulesRequestSummaryOneOf1 getRulesRequestSummaryOneOf1() throws ClassCastException {
        return (RulesRequestSummaryOneOf1)super.getActualInstance();
    }

}

